language: node_js
notifications:
  email: false
cache:
  directories:
    - $HOME/.npm
jobs:
  include:
  - stage: test
    script:
    - npm run lint
    - npm test
    - npm run coverage
  - stage: deploy
    install: true
    if: tag IS present
    script:
    - echo 'Deploying to NOW'
    - npm install -g now
    - npm run deploy && npm run alias
